server:
  port: 3344

spring:
  application:
    name: cloud-config-center         # 注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: git@github.com:zhaolijian/cloud2020_config.git
          # 搜索目录
          search-paths:
            - springcloud-config
      # 读取分支
      label: master

eureka:
  client:
#    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka   #集群版
