server:
  port: 8001

spring:
  application:
#    服务名称
    name: cloud-payment-service
  zipkin:
    # 监控的数据通过该url可以看到
    base-url: http://localhost:9411
  sleuth:
    sampler:
      # 采样率值介于0到1之间，1表示全部采集
      probability: 1
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource   # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver     # mysql驱动包
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

eureka:
  client:
    register-with-eureka: true   # 是否注册到eureka server
    fetch-registry: true         # 是否从eureka server中获取已有的注册信息，单节点无所谓，集群必须配置true才能配合ribbon使用负载均衡
    service-url:
#      eureka server url地址
#      defaultZone: http://localhost:7001/eureka      # 单机版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka   #集群版
  instance:
    # 修改服务名称，原来为： 172.19.99.221:cloud-payment-service:8001， 改后为payment8001
    instance-id: payment8001
    # 访问路径可以显示ip地址
    prefer-ip-address: true
    # eureka客户端向服务端发送心跳的时间间隔(单位s)，默认30s
#    lease-renewal-interval-in-seconds: 1
    # eureka服务端在收到最后一次心跳后等待时间上限，单位为s，默认90s，超时将剔除服务
#    lease-expiration-duration-in-seconds: 2

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.entities   # 所有entity别名类所在包