server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true                 # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
      # 路由是有id、uri、predicate(断言)、一系列filter(过滤器)组成
      routes:
        - id: payment_routh             # 路由的id，没有固定规则但是要求唯一，建议配合服务名
          # localhost:9527即调用该微服务，比如localhost:9527/payment/get/1即调用localhost:8001/payment/get/1或者localhost:8002/payment/get/1
          uri: lb://cloud-payment-service # lb://表示基于服务注册的负载均衡
#          uri: http://localhost:8001    # 匹配后提供服务的路由地址（手动执行服务实例，太笨拙）
          predicates:
            - Path=/payment/get/**      # 断言，路径相匹配的进行路由

        - id: payment_routh2
          uri: lb://cloud-payment-service # lb://表示基于服务注册的负载均衡
#          uri: http://localhost:8002（手动执行服务实例，太笨拙）
          predicates:
            - Path=/payment/lb/**
#            - After=2020-12-05T14:35:53.747+08:00[Asia/Shanghai]       # 在这个时间点之后该路由才生效
#            - Before=2020-12-05T15:35:53.747+08:00[Asia/Shanghai]       # 在这个时间点之前该路由才生效
#            - Between=2020-12-05T15:35:53.747+08:00[Asia/Shanghai],2020-12-31T15:35:53.747+08:00[Asia/Shanghai]       # 在这个时间点之间该路由才生效
#            - Cookie=username,zzyy           # cookie键值对，只有带上cookie才能使用网关，否则404
#            - Method=GET                     # get方法才允许访问
#            - Header=X-Request-Id, \d+       # 请求头要有X-Request-Id属性并且值为正数的正则表达式
#            - Query=username, \d+            # 要有参数名username并且值是正数才能路由
#            - Host=**.atguigu.com             # 限制主机名

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka   #集群版