server:
  port: 8802

spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      binders:                       # 配置要绑定的rabbitmq的服务信息
        defaultRabbit:               # 定义的名称，用于binding整合
          type: rabbit               # 消息组件类型
          environment:               # 设置rabbitmq的相关的环境配置
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings:                      # 服务的整合处理
        input:                       # 通道的名称
          destination: studyExchange # 要使用的Exchange名称定义,消息从这取
          content-type: application/json    # 设置消息类型：json，文本设置为"text/plain"
          binder: defaultRabbit             # 设置要绑定的消息服务的具体设置
          group: atguiguA                   # 微服务分组，同一个组只能有一个服务消费，不同组可以重复消费

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka   #集群版
  instance:
    lease-renewal-interval-in-seconds: 2      # 心跳间隔时间（默认30s）
    lease-expiration-duration-in-seconds: 5   # eureka服务端在收到最后一次心跳后等待时间上限，单位为s，默认90s，超时将剔除服务
    instance-id: send-8802.com               # 信息列表显示的主机名称
    prefer-ip-address: true                   # 访问的路径变为ip地址